# SEO
logo: /assets/img/MakerFX_with_text.png

# Company Information included in footer left side
company_name: MakerFX Makerspace
address_line: 8600 Commodity Cirle \#158, Orlando FL 32819
telephone_number: 407.634.6257
company_email: info@makerfx.org
google_map: https://www.google.com/maps/place/MakerFX+Makerspace/@28.4452794,-81.4343291,17z/data=!3m1!4b1!4m5!3m4!1s0x88e77e792d55b5cd:0x564df7bdacb237b0!8m2!3d28.4452794!4d-81.4321404

# Social Links
facebook_link: https://www.facebook.com/makerfxspace
twitter_link: https://twitter.com/makerfx
instagram_link: https://www.instagram.com/makerfxspace/
flickr_link: https://www.flickr.com/groups/makerfx/
slack_link: https://makereffect.slack.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap
