# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MakerFX Makerspace
email: admin@makerfx.org
description: > # this means to ignore newlines until "baseurl:"
  MakerFX Makerspace is a unique makerspace in South Orlando.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://www.makerfx.org"

# Company Information
company_name: MakerFX Makerspace
address_line: 8600 Commodity Cirle \#158, Orlando FL 32819
telephone_number: 1.407.634.6257
company_email: info@makerfx.org
google_map: https://www.google.com/maps/place/MakerFX+Makerspace/@28.4452794,-81.4343291,17z/data=!3m1!4b1!4m5!3m4!1s0x88e77e792d55b5cd:0x564df7bdacb237b0!8m2!3d28.4452794!4d-81.4321404

# Social Links
facebook_link: https://www.facebook.com/makerfxspace
twitter_link: https://twitter.com/makerfx
instagram_link: https://www.instagram.com/makerfxspace/
flickr_link: https://www.flickr.com/groups/makerfx/
slack_link: https://makereffect.slack.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
